#ifndef CAMERAEFFECTTYPE_H
#define CAMERAEFFECTTYPE_H

enum CameraEffectType
{
    EFFECT_TEST,
    EFFECT_LOW_SHAKE,
    EFFECT_VERY_LOW_SHAKE,
    EFFECT_HARD_SHAKE
};

#endif // CAMERAEFFECTTYPE_H
