#ifndef BLOCKINTERACTIONTYPE_H
#define BLOCKINTERACTIONTYPE_H

enum BlockInteractionType
{
    BI_NO_INTERACTION,
    BI_CHEST,
    BI_PORTAL,
    BI_SAVEPOINT,
    BI_START_BOSS1,
    BI_START_BOSS1_FINAL
};

#endif // BLOCKINTERACTIONTYPE_H
