#ifndef SERIALIZABLETYPE_H
#define SERIALIZABLETYPE_H

#include "Libs/json.hpp"

using json = nlohmann::json;

enum SerializableType
{
    SERIALIZE_ROOM,
    SERIALIZE_ITEM_LIST,
    SERIALIZE_PLAYERINFOS,
    SERIALIZE_CIRCLEMOB,
    SERIALIZE_CROSSLASERMOB,
    SERIALIZE_PLAYER,
    SERIALIZE_PUNCHBALLMOB,
    SERIALIZE_SQUAREMOB,
    SERIALIZE_TRACKERMOB,
    SERIALIZE_NONE
};

SerializableType fromJson(const json & j);

#endif // SERIALIZABLETYPE_H
